name: Bandit Security Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust if needed

    - name: Install dependencies
      run: pip install bandit

    - name: Run Bandit Security Scan
      run: bandit -r .  # Recursively scan the entire project

    - name: Display Bandit Report
      run: |
        echo "Bandit scan complete. See above for results."
